[143] bump qt version and emsdk version (#565)
https://doc.qt.io/qt-6/wasm.html#installing-emscripten

`mogan.js` should be patched as below:

```js

var createQtAppInstance = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createQtAppInstance) {
  createQtAppInstance = createQtAppInstance || {};

/* content generated by emsdk */
  return createQtAppInstance.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createQtAppInstance;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createQtAppInstance; });
else if (typeof exports === 'object')
  exports["createQtAppInstance"] = createQtAppInstance;
```

after patching, errors occurs when starting:
```

TypeError: createQtAppInstance(...) is undefined
RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
The qtContainerElements module property was not set or is invalid. Proceeding with no screens.
no screens available, assuming 24-bit color
Welcome to TeXmacs 2.1.2
------------------------------------------------------------------------------
Installation completed successfully !
I will now start up the editor
------------------------------------------------------------------------------
Benchmark 1
832040
Time: 45
Booting TeXmacs kernel functionality
------------------------------------------------------
Initialization done
------------------------------------------------------
Benchmark 2
832040
Time: 284
------------------------------------------------------
Forcing delayed loads
time: 1603
memory: 3131008 bytes
------------------------------------------------------
Cannot create window: no screens available
Aborted()
```