[38_7] svg: remove imagemagick as the converter to ps/pdf
## What
as title

## Why
It does not work on Debian 12
```
> convert TeXmacs/misc/pixmaps/modern/24x24/main/tm_cloud.svg /tmp/test.pdf                                                                                                       
convert: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/426.
Exception: convert exited with 1
```

## How to test your changes?
No need to test.